### ISSUE TITLE
파일 시간 받아오기

### ISSUE THREAD

**Issue by droplet92** [droplet92/Assignment2#2]
파일 시간을 받아오는 기능 구현

**Comment by cocoapi** [comment]
이거 일단 제가할게요

**Comment by droplet92** [comment]
pr 머지되어 이슈 닫습니다.

**Comment by droplet92** [comment]
오류 발견했습니다. 수정해주세요

**Comment by droplet92** [comment]
필요 시 다시 열어주세요!

**Comment by droplet92** [comment]
디폴트가 assign yourself인 줄 알았네요 😀 
제가 했으니 assignee에 추가했습니다.

**Comment by droplet92** [comment]
participant 초대해서 asignee 변경했습니다.
